services:
  # Main application only - for local testing
  fraud-detection-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
