services:
  # Main application
  fraud-detection-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  # MLflow tracking server (simplified)
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    command: >
      sh -c "pip install mlflow && 
      mlflow server --backend-store-uri sqlite:///mlflow.db 
                   --default-artifact-root ./mlruns 
                   --host 0.0.0.0 
                   --port 5000"
    restart: unless-stopped

  # Redis (using official image)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # PostgreSQL (using official image)
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fraud_detection
      - POSTGRES_USER=fraud_user
      - POSTGRES_PASSWORD=fraud_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
